# Generated by Django 4.1.7 on 2023-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("company", models.TextField(null=True, verbose_name="Compañia")),
                ("identification", models.CharField(max_length=200, verbose_name="id")),
                ("href", models.URLField(max_length=128)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="latitud"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="longitud"
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="Ciudad")),
                ("country", models.CharField(max_length=200, verbose_name="Pais")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Red",
                "verbose_name_plural": "Redes",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("identification", models.CharField(max_length=200, verbose_name="id")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="latitud"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="longitud"
                    ),
                ),
                (
                    "free_bikes",
                    models.IntegerField(verbose_name="bicicletas disponibles"),
                ),
                (
                    "empty_slots",
                    models.IntegerField(verbose_name="espacios disponibles"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Dirección")),
                ("ebikes", models.IntegerField(verbose_name="bicicletas electricas")),
                ("has_ebikes", models.BooleanField()),
                (
                    "normal_bikes",
                    models.IntegerField(verbose_name="bicicletas normales"),
                ),
                ("payment", models.TextField(null=True, verbose_name="Formas de pago")),
                ("payment_terminal", models.BooleanField()),
                (
                    "post_code",
                    models.CharField(max_length=200, verbose_name="numero de post"),
                ),
                ("renting", models.IntegerField(verbose_name="bicicletas rentadas")),
                (
                    "returning",
                    models.IntegerField(verbose_name="bicicletas regresadas"),
                ),
                ("slots", models.IntegerField(verbose_name="cantidad de espacios")),
                ("uid", models.CharField(max_length=200, verbose_name="numero uid")),
                ("date", models.DateTimeField()),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estacion",
                "verbose_name_plural": "Estaciones",
                "ordering": ["-created"],
            },
        ),
    ]
