# Generated by Django 4.1.7 on 2023-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_proyecto", models.IntegerField(verbose_name="Id del proyecto")),
                (
                    "nombre_proyecto",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "tipo_proyecto",
                    models.CharField(max_length=200, verbose_name="Tipo"),
                ),
                ("region", models.CharField(max_length=200, verbose_name="Región")),
                (
                    "tipologia",
                    models.CharField(max_length=200, verbose_name="Tipología"),
                ),
                ("titular", models.CharField(max_length=200, verbose_name="Titular")),
                (
                    "inversion",
                    models.DecimalField(
                        decimal_places=4, max_digits=9, verbose_name="Inversión(MMU$)"
                    ),
                ),
                ("fecha_ingreso", models.DateField(verbose_name="Fecha de Ingreso")),
                (
                    "estado",
                    models.CharField(
                        max_length=200, verbose_name="Estado del proyecto"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-fecha_ingreso"],
            },
        ),
    ]
