# Generated by Django 4.1.7 on 2023-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarea2", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proyecto",
            options={
                "ordering": ["id_proyecto"],
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="nombre_proyecto",
            field=models.CharField(max_length=255, verbose_name="Nombre del proyecto"),
        ),
    ]
