# Generated by Django 4.1.7 on 2023-02-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarea2", "0002_alter_proyecto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="nombre_proyecto",
            field=models.TextField(verbose_name="Nombre del proyecto"),
        ),
    ]
